from pyvis.network import Network
try:
    from .taint_graph import NodeType
except ImportError:
    from taint_graph import NodeType
# Generated by GPT-5.6 Luna

def visualize_graph(graph, output_path="taint_graph.html"):
    visual_graph = Network(
        height="800px",
        width="100%",
        directed=True,
        notebook=False,
    )

    colors = {
        NodeType.SOURCE: "#e74c3c",
        NodeType.PROPAGATOR: "#f1c40f",
        NodeType.SANITIZER: "#2ecc71",
        NodeType.SINK: "#3498db",
    }

    for node in graph.nodes:
        visual_graph.add_node(
            node.id,
            label=f"{node.type.value}\n{node.value}",
            title=node.value,
            color=colors[node.type],
        )

    for source, target in graph.edges:
        visual_graph.add_edge(
            source.id,
            target.id,
            arrows="to",
        )

    visual_graph.write_html(output_path)